ansible_user: ec2-user
ansible_password: "DevOps321
MONGODB_HOST: mongodb-"{{ env }}".siddharthais.online
CATALOGUE_HOST: catalogue-"{{ env }}".siddharthais.online
REDIS_HOST: redis-"{{ env }}".siddharthais.online
USER_HOST: user-"{{ env }}".siddharthais.online
CART_HOST: cart-"{{ env }}".siddharthais.online
MYSQL_HOST: mysql-"{{ env }}".siddharthais.online
SHIPPING_HOST: shipping-"{{ env }}".siddharthais.online
RABBITMQ_HOST: rabbitmq-"{{ env }}".siddharthais.online
PAYMENT_HOST: payment-"{{ env }}".siddharthais.online