[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.siddharthais.online

[redis]
redis-dev.siddharthais.online

[user]
user-dev.siddharthais.online

[cart]
cart-dev.siddharthais.online

[mysql]
mysql-dev.siddharthais.online

[shipping]
shipping-dev.siddharthais.online

[rabbitmq]
rabbitmq-dev.siddharthais.online

[payment]
payment-dev.siddharthais.online

[frontend]
frontend-dev.siddharthais.online